export enum WeatherKindEnums {
    SUNNY = 'Sunny',
    PARTLY_CLOUDY = 'Partly cloudy',
    CLOUDY = 'Cloudy',
    VERY_CLOUDY = 'Very Cloudy',
    FOG = 'Fog',
    LIGHT_SHOWERS = 'Light Showers',
    LIGHT_SLEET_SHOWERS = 'Light Sleet Showers',
    LIGHT_SLEET = 'Light Sleet',
    THUNDERY_SHOWERS = 'Thundery Showers',
    LIGHT_SNOW = 'Light Snow',
    HEAVY_SNOW = 'Heavy Snow',
    LIGHT_RAIN = 'Light Rain',
    HEAVY_SHOWERS = 'Heavy Showers',
    HEAVY_RAIN = 'Heavy Rain',
    LIGHT_SNOW_SHOWERS = 'Light Snow Showers',
    HEAVY_SNOW_SHOWERS = 'Heavy Snow Showers',
    THUNDERY_HEAVY_RAIN = 'Thundery Heavy Rain',
    THUNDERY_SNOW_SHOWERS = 'Thundery Snow Showers'
}